version: "3.7"

services:
  samba:
    image: "dperson/samba:aarch64"
    container_name: samba
    environment:
       TZ: "Asia/Tokyo"
       WORKGROUP: "WORKGROUP"
    network_mode: "host"
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /opt/MediaFiles:/mnt1:z
    command: >
      -g "force user = user"
      -g "force group = group"
      -s "MediaFiles;/mnt2;yes;no;no;user"
      -u "user;passwd"
      -r
